Client:
    type: entity
    table: client
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        login:
            type: string
            nullable: false
            length: 20
            options:
                fixed: true
        password:
            type: string
            nullable: false
            length: 20
            options:
                fixed: true
        civility:
            type: string
            nullable: true
            length: 20
            options:
                fixed: true
        firstname:
            type: string
            nullable: true
            length: 20
            options:
                fixed: true
        name:
            type: string
            nullable: true
            length: 20
            options:
                fixed: true
        address:
            type: string
            nullable: true
            length: 50
            options:
                fixed: true
        cp:
            type: decimal
            nullable: true
            precision: 5
            scale: 0
        city:
            type: string
            nullable: true
            length: 30
            options:
                fixed: true
        country:
            type: string
            nullable: true
            length: 30
            options:
                fixed: true
        tel:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
        email:
            type: string
            nullable: true
            length: 30
            options:
                fixed: true
    lifecycleCallbacks: {  }
