Fruit:
    type: entity
    table: fruit
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 20
            options:
                fixed: true
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
        color:
            type: string
            nullable: true
            length: 20
            options:
                fixed: true
    lifecycleCallbacks: {  }
